apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grandiosoft-ingress
spec:
  rules:
  - host: grandiosoft.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grandiosoft-service
            port:
              number: 80
