apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandiosoft-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grandiosoft-web
  template:
    metadata:
      labels:
        app: grandiosoft-web
    spec:
      containers:
      - name: web
        image: grandiosoft-website:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
